### PR TITLE
Week 8: Style + provide responsiveness to sign-in & sign-up forms

### LINKED ISSUE #188: Provide further responsive styling to sign-in & sign-up forms

### PR DESCRIPTION
**Pull request by asaiapalacios**
closes #188 

- centered logo & title
- provided a precise link to only "Email" & "Sign In" -> no longer links the whole text
- added color to these links (our yellow wireframe color)
- outlined buttons to provide a bit of a pop
- provided some responsiveness (work in progress)
- removed JSX elements not in use 
- cleaned up styling properties

desktop version
desktop-sign-in-version

version for smaller screens
sign-in-version

### CODE REVIEW

**Comment by badgerbadgers** [comment]
Looks great! Just one small issue is that I white space, adding width 100% seems to get rid of it for me.
Screen Shot 2022-09-16 at 9 09 21 AM

Width 100%
Screen Shot 2022-09-16 at 9 09 08 AM

**Comment by asaiapalacios** [comment]
I'm wondering if this is an operating system specific issue, because I'm not getting the white space along the edges for both Chrome and Firefox browsers. Can anyone else test this for us, and let us know if you are also getting the white space along the edges? Thanks

**Comment by badgerbadgers** [comment]
> I'm wondering if this is an operating system specific issue, because I'm not getting the white space along the edges for both Chrome and Firefox browsers. Can anyone else test this for us, and let us know if you are also getting the white space along the edges? Thanks...I'm also wondering how it'll render for the deployed chat app version.

So this looks fine for me on refresh. LGTM.

**Review by badgerbadgers — APPROVED** [review]
LGTM

**Pull request merged**
