### PR TITLE
Week 8: Sound button when clicked indicates desired behavior to user (on/off)

### PR DESCRIPTION
**Pull request by asaiapalacios**
upon requested change, I reversed it so the sound button indicates the desired behavior to the user:

- when app starts w/no sound -> display button w/sound so user can select this option from default disabled state
- when have sound -> display button w/no sound (icon crossed out) to indicate user can select this button to mute sound

### CODE REVIEW

**Comment by LawrenceELee** [comment]
First, you link the PR to the issue ticket. Then after you merge the PR, it will automatically close the issue ticket.

**Comment by asaiapalacios** [comment]
@LawrenceELee the branch had already been deleted. I reopened & made new changes. It needs to be linked to here: https://github.com/badgerbadgers/ctd-sparrow-chat-app/pull/176

**Comment by badgerbadgers** [comment]
This should be fine the branch got deleted is all, new PR or issue shouldn't be a big deal.

**Review by viniciuspietscher — APPROVED** [review]
:100:  thank you for changing it back!

**Pull request merged**
