### PR TITLE
add firebase basic configuration and test component

### PR DESCRIPTION
**Pull request by viniciuspietscher**
Hi team,

I created a test component to test sending a message to Firebase. There is also a .env example file where you need to rename it to .env and include your own API keys.

Please let me know if any of you encounter any issues.

Closes: #4 

Edit:
To run this branch in your machine:
1. Create a new Firebase project, copy your API keys, add Firestore to your project;
2. Rename the `env-example` to `.env` and substitute the API keys;
3. Run `npm install`
4. Run `npm start`

### CODE REVIEW

**Review by asaiapalacios — APPROVED** [review]
This run through was helpful in testing the branch. My message was received successfully when checking the Firestore console. Thumbs up.

**Comment by badgerbadgers** [comment]
tested and approved yeah good practice Vini!

**Review by badgerbadgers — APPROVED** [review]
LGTM!

**Comment by LawrenceELee** [comment]
Test

**Review by badgerbadgers — APPROVED** [review]
LGTM reapproving, since I have already tested this feature.

**Pull request merged**
