### PR TITLE
Week 6: Add sound for send-message and toggle button

### LINKED ISSUE #160: Sound: to enhance the user experience
- apply to certain elements to enhance UX
- experiment what element(s) to use sound for

### PR DESCRIPTION
**Pull request by asaiapalacios**
closes #160 

Note: made edits based on feedback. PR is no longer for testing purposes. Seeking testing & approval to merge to our main branch.

For setup, run: `npm install use-sound`

- removed sound for sign-in and sign-out buttons. 
- used Josh W. Comeau's [sound files](https://github.com/joshwcomeau/use-sound/tree/master/stories/sounds), creator of use-sound React hook, for send-message and toggle button sounds

### CODE REVIEW

**Comment by viniciuspietscher** [comment]
I like the sounds a lot! And it works great!

I'm just getting a warning on my console:
image

I tried moving the imports and the useSound hook to the navbar instead of the context file and it still works and I didn't get a warning.
image

**Comment by asaiapalacios** [comment]
Thanks, Vini, for the input. I'll go ahead and make those changes.

**Review by viniciuspietscher — APPROVED** [review]
:100:

**Comment by viniciuspietscher** [comment]
Leaving this here for reference

https://github.com/joshwcomeau/use-sound/issues/92

**Pull request merged**
